version: '3.1'

services:
  php:
    # first version image: php:7.4-apache
    build:
      context: . #directorio actual
      dockerfile: Dockerfile #leera y construirar la imagne con la extension agregar en Dockerfile
    ports: #ejecuccion del puerto local:puerto server
      - 80:80
    volumes:  #copiar archivos_local:archivos_server
      - ./src:/var/www/html/
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080